export const bossList = [
    { name: "Moss Mother (1/2)", location: "Moss Grotto", flag: "defeatedMossMother" },
    { name: "Bell Beast", location: "", flag: "defeatedBellBeast" },
    { name: "Lace (1/2)", location: "", flag: "defeatedLace1" },
    { name: "Fourth Chorus", location: "", flag: "defeatedSongGolem" },
    { name: "Savage Beastfly (1/2)", location: "", flag: "defeatedBoneFlyerGiant" },
    { name: "Sister Splinter", location: "", flag: "defeatedSplinterQueen" },
    { name: "Skull Tyrant (1/2)", location: "", flag: "skullKingDefeated" },
    { name: "Skull Tyrant (2/2)", location: "", flag: "" },
    { name: "Moorwing", location: "", flag: "defeatedVampireGnatBoss" },
    { name: "Widow", location: "", flag: "" },
    { name: "Moss Mother (2/3)", location: "", flag: "" },
    { name: "Savage Beastfly (2/2)", location: "", flag: "defeatedBoneFlyerGiantGolemScene" },
    { name: "Great Conchflies", location: "", flag: "defeatedCoralDrillers" },
    { name: "Last Judge", location: "", flag: "defeatedLastJudge" },
    { name: "Phantom", location: "", flag: "defeatedPhantom" },
    { name: "Cogwork Dancers", location: "", flag: "defeatedCogworkDancers" },
    { name: "Trobbio", location: "", flag: "defeatedTrobbio" },
    { name: "Garmond and Zaza", location: "", flag: "garmondLibraryDefeatedHornet" },
    { name: "Signis and Gron", location: "", flag: "" },
    { name: "The Unravelled", location: "", flag: "" },
    { name: "Disgraced Chef Lugoli", location: "", flag: "defeatedRoachkeeperChef" },
    { name: "Father Of The Flame", location: "", flag: "defeatedWispPyreEffigy" },
    { name: "Groal the Great", location: "", flag: "" },
    { name: "Voltvyrm", location: "", flag: "defeatedZapCoreEnemy" },
    { name: "Raging Conchfly", location: "", flag: "defeatedCoralDrillerSolo" },
    { name: "First Sinner", location: "", flag: "defeatedFirstWeaver" },
    { name: "Broodmother", location: "", flag: "defeatedBroodMother" },
    { name: "Second Sentinel", location: "", flag: "defeatedSongChevalierBoss" },
    { name: "Shakra", location: "", flag: "" },
    { name: "Lace (2/2)", location: "", flag: "defeatedLaceTower" },
    { name: "Grand Mother Silk", location: "", flag: "" },
    { name: "Bell Eater", location: "", flag: "" },
    { name: "Moss Mother (3/3)", location: "", flag: "defeatedMossEvolver" },
    { name: "Lost Garmond", location: "", flag: "garmondBlackThreadDefeated" },
    { name: "Crawfather", location: "", flag: "" },
    { name: "Plasmified Zongo", location: "", flag: "" },
    { name: "Watcher At the Edge", location: "", flag: "" },
    { name: "Palestag", location: "", flag: "defeatedWhiteCloverstag" },
    { name: "Clover Dancers", location: "", flag: "defeatedCloverDancers" },
    { name: "Gurr The Outcast", location: "", flag: "" },
    { name: "Tormented Trobbio", location: "", flag: "defeatedTormentedTrobbio" },
    { name: "Pinstress", location: "", flag: "PinstressPeakBattleAccepted" },
    { name: "Shrine Guardian Seth", location: "", flag: "defeatedSeth" },
    { name: "Nyleth", location: "", flag: "defeatedFlowerQueen" },
    { name: "Skarrsinger Karmelita", location: "", flag: "defeatedAntQueen" },
    { name: "Crust King Khann", location: "", flag: "defeatedCoralKing" },
    { name: "Summoned Saviour", location: "", flag: "" },
    { name: "Lost Lace", location: "", flag: "" },
];