export const abilityList = [
    { name: "Swift Step", location: "477915", flag: "hasDash" },
    { name: "Drifter's Cloak", location: "477971", flag: "hasBrolly" },
    { name: "Cling Grip", location: "478189", flag: "hasWalljump" },
    { name: "Needle Strike", location: "478510", flag: "hasChargeSlash" },
    { name: "Clawline", location: "478714", flag: "hasQuill" },
    { name: "Faydown Cloak", location: "479103", flag: "hasDoubleJump" },
    { name: "Silk Soar", location: "479288", flag: "hasSuperJump" },
    { name: "Sylphsong", location: "479654", flag: "HasSeenEvaHeal" },
    { name: "Needolin", location: "478199", flag: "hasNeedolin" },
];

export const bossList = [
    { name: "Moss Mother (1/3)", location: "476904", flag: "defeatedMossMother", flagType: "boolean" },
    { name: "Bell Beast", location: "477879", flag: "defeatedBellBeast", flagType: "boolean" },
    { name: "Lace (1/2)", location: "476915", flag: "defeatedLace1", flagType: "boolean" },
    { name: "Fourth Chorus", location: "477978", flag: "defeatedSongGolem", flagType: "boolean" },
    { name: "Savage Beastfly (1/2)", location: "478844", flag: "defeatedBoneFlyerGiant", flagType: "boolean" },
    { name: "Sister Splinter", location: "478137", flag: "defeatedSplinterQueen", flagType: "boolean" },
    { name: "Skull Tyrant (1/2)", location: "478136", flag: "skullKingDefeated", flagType: "boolean" },
    { name: "Skull Tyrant (2/2)", location: "479655", flag: "skullKingKilled", flagType: "boolean" },
    { name: "Moorwing", location: "478453", flag: "defeatedVampireGnatBoss", flagType: "boolean" },
    { name: "Craggler", location: "478088", flag: "Roof Crab", flagType: "journal" },
    { name: "Widow", location: "478138", flag: "visitedBellhartSaved", flagType: "boolean" },
    {
        name: "Moss Mother (2/3)", location: "478440", flag: "Moss Mother", flagType: "journal", check: (playerData) => {
            const kills = playerData?.EnemyJournalKillData?.list?.find((entry) => entry.Name === "Mossbone Mother"
            )?.Record.Kills || 0;
            return kills >= 3;
        }
    },
    { name: "Savage Beastfly (2/2)", location: "478019", flag: "defeatedBoneFlyerGiantGolemScene", flagType: "boolean" },
    { name: "Great Conchflies", location: "478506", flag: "defeatedCoralDrillers", flagType: "boolean" },
    { name: "Last Judge", location: "478545", flag: "defeatedLastJudge", flagType: "boolean" },
    { name: "Phantom", location: "478370", flag: "defeatedPhantom", flagType: "boolean" },
    { name: "Cogwork Dancers", location: "478606", flag: "defeatedCogworkDancers", flagType: "boolean" },
    { name: "Trobbio", location: "478690", flag: "defeatedTrobbio", flagType: "boolean" },
    { name: "Garmond and Zaza", location: "479361", flag: "Garmond_Zaza", flagType: "journal" },
    { name: "Signis and Gron", location: "478831", flag: "Dock Guard Thrower", flagType: "journal" },
    { name: "The Unravelled", location: "480354", flag: "wardBossDefeated", flagType: "boolean" },
    { name: "Disgraced Chef Lugoli", location: "478992", flag: "defeatedRoachkeeperChef", flagType: "boolean" },
    { name: "Father Of The Flame", location: "479155", flag: "defeatedWispPyreEffigy", flagType: "boolean" },
    { name: "Groal the Great", location: "478861", flag: "DefeatedSwampShaman", flagType: "boolean" },
    { name: "Voltvyrm", location: "479223", flag: "defeatedZapCoreEnemy", flagType: "boolean" },
    { name: "Raging Conchfly", location: "479227", flag: "defeatedCoralDrillerSolo", flagType: "boolean" },
    { name: "First Sinner", location: "479023", flag: "defeatedFirstWeaver", flagType: "boolean" },
    { name: "Broodmother", location: "479255", flag: "defeatedBroodMother", flagType: "boolean" },
    { name: "Second Sentinel", location: "479253", flag: "defeatedSongChevalierBoss", flagType: "boolean" },
    { name: "Shakra", location: "479822", flag: "Shakra", flagType: "journal" },
    { name: "Lace (2/2)", location: "479088", flag: "defeatedLaceTower", flagType: "boolean" },
    { name: "Grand Mother Silk", location: "479099", flag: "Silk Boss", flagType: "journal" },
    { name: "Bell Eater", location: "479264", flag: "Giant Centipede", flagType: "journal" },
    {
        name: "Moss Mother (3/3)", location: "481810", flag: "Moss Mother", flagType: "journal", check: (playerData) => {
            const kills = playerData?.EnemyJournalKillData?.list?.find((entry) => entry.Name === "Mossbone Mother"
            )?.Record.Kills || 0;
            return kills == 4;
        }
    },
    { name: "Lost Garmond", location: "479452", flag: "garmondBlackThreadDefeated", flagType: "boolean" },
    { name: "Crawfather", location: "479578", flag: "Crawfather", flagType: "journal" },
    { name: "Plasmified Zango", location: "479273", flag: "BlueScientistDead", flagType: "boolean" },
    { name: "Watcher At the Edge", location: "480326", flag: "Coral Warrior Grey", flagType: "journal" },
    { name: "Palestag", location: "479408", flag: "defeatedWhiteCloverstag", flagType: "boolean" },
    { name: "Clover Dancers", location: "479427", flag: "defeatedCloverDancers", flagType: "boolean" },
    { name: "Gurr The Outcast", location: "479467", flag: "defeatedAntTrapper", flagType: "boolean" },
    { name: "Tormented Trobbio", location: "479377", flag: "defeatedTormentedTrobbio", flagType: "boolean" },
    { name: "Pinstress", location: "479464", flag: "PinstressPeakBattleAccepted", flagType: "boolean" },
    { name: "Shrine Guardian Seth", location: "479401", flag: "defeatedSeth", flagType: "boolean" },
    { name: "Nyleth", location: "479404", flag: "defeatedFlowerQueen", flagType: "boolean" },
    { name: "Skarrsinger Karmelita", location: "479198", flag: "defeatedAntQueen", flagType: "boolean" },
    { name: "Crust King Khann", location: "479392", flag: "defeatedCoralKing", flagType: "boolean" },
    { name: "Lost Lace", location: "479471", flag: "Lost Lace", flagType: "journal" },
    { name: "Summoned Saviour", location: "479740", flag: "Abyss Mass", flagType: "journal" },
];

export const crestList = [
    { name: "Hunter's Crest", location: "", flag: "Hunter" },
    { name: "Hunter's Crest (Upgrade)", location: "478229", flag: "Hunter_v2" },
    { name: "Hunter's Crest (Final Upgrade)", location: "479653", flag: "Hunter_v3" },
    { name: "Reaper Crest", location: "478156", flag: "Reaper" },
    { name: "Wanderer Crest", location: "478240", flag: "Wanderer" },
    { name: "Beast Crest", location: "478020", flag: "Warrior" },
    { name: "Witch Crest", location: "478815", flag: "Witch" },
    { name: "Architect Crest", location: "478745", flag: "Toolmaster" },
    { name: "Shaman Crest", location: "479384", flag: "Spell" },
];

export const vesticrestList = [
    { name: "Vesticrest (+Yellow)", location: "479145", flag: "UnlockedExtraYellowSlot" },
    { name: "Vesticrest (+Blue)", location: "479434", flag: "UnlockedExtraBlueSlot" },
]

export const mapList = [
    { name: "Mosslands", location: "479514", flag: "HasMossGrottoMap" },
    { name: "The Marrow", location: "479515", flag: "HasBoneforestMap" },
    { name: "Deep Docks", location: "479516", flag: "HasDocksMap" },
    { name: "Hunter's March", location: "479518", flag: "HasHuntersNestMap" },
    { name: "Far Fields", location: "479517", flag: "HasWildsMap" },
    { name: "Greymoor", location: "479527", flag: "HasGreymoorMap" },
    { name: "Bellhart", location: "479529", flag: "HasBellhartMap" },
    { name: "Shellwood", location: "479530", flag: "HasShellwoodMap" },
    { name: "Wormways", location: "479523", flag: "HasCrawlMap" },
    { name: "Weavenest Atla", location: "478227", flag: "HasWeavehomeMap" },
    { name: "Blasted Steps", location: "479673", flag: "HasJudgeStepsMap" },
    { name: "Sinner's Road", location: "479526", flag: "HasHangMap" },
    { name: "Grand Gate", location: "478548", flag: "HasSongGateMap" },
    { name: "Underworks", location: "478551", flag: "HasCitadelUnderstoreMap" },
    { name: "Choral Chambers", location: "479733", flag: "HasCoralMap" },
    { name: "Whispering Vaults", location: "478628", flag: "HasLibraryMap" },
    { name: "Whiteward", location: "478920", flag: "HasWardMap" },
    { name: "Cogwork Core", location: "478612", flag: "HasCogMap" },
    { name: "Memorium", location: "479107", flag: "HasArboriumMap" },
    { name: "High Halls", location: "478907", flag: "HasHallsMap" },
    { name: "The Slab", location: "478468", flag: "HasSlabMap" },
    { name: "Mount Fay", location: "479525", flag: "HasPeakMap" },
    { name: "Bilewater", location: "479528", flag: "HasSwampMap" },
    { name: "Putrified Ducts", location: "479128", flag: "HasAqueductMap" },
    { name: "Sands of Karak", location: "479524", flag: "HasCoralMap" },
    { name: "The Cradle", location: "479095", flag: "HasCradleMap" },
    { name: "Verdania", location: "479382", flag: "HasCloverMap" },
    { name: "The Abyss", location: "479282", flag: "HasAbyssMap" },
];

export const needleUpgradeList = [
    { name: "#1: Sharpened Needle", flag: "nailUpgrades", index: 1 },
    { name: "#2: Shining Needle", flag: "nailUpgrades", index: 2 },
    { name: "#3: Hivesteel Needle", flag: "nailUpgrades", index: 3 },
    { name: "#4: Pale Steel Needle", flag: "nailUpgrades", index: 4 },
];

export const silkSkillsList = [
    { name: "Silkspear", location: "477871", flag: "hasNeedleThrow" },
    { name: "Thread Storm", location: "478061", flag: "hasThreadSphere" },
    { name: "Cross Stitch", location: "478371", flag: "hasParry" },
    { name: "Sharpdart", location: "479079", flag: "hasHarpoonDash" },
    { name: "Rune Rage", location: "479025", flag: "hasSilkBomb" },
    { name: "Pale Nails", location: "479606", flag: "hasSilkCharge" },
];

export const ToolList = [
    // red tools
    { name: "Straight Pin", location: "477899", saveName: "Straight Pin" },
    { name: "Threefold Pin", location: "478058", saveName: "Tri Pin" },
    { name: "Sting Shard", location: "477917", saveName: "Sting Shard" },
    { name: "Tacks", location: "478365", saveName: "Tack" },
    { name: "Longpin", location: "478158", saveName: "Harpoon" },
    { name: "Curveclaw", location: "478604", saveName: "Curve Claws" },
    { name: "Curvesickle", location: "479675", saveName: "Curve Claws Upgraded" },
    { name: "Throwing Ring", location: "479242", saveName: "Shakra Ring" },
    { name: "Pimpillo", location: "478964", saveName: "Pimpilo" },
    { name: "Conchcutter", location: "479230", saveName: "Conch Drill" },
    { name: "Silkshot (Forge Daughter)", location: "479364", saveName: "WebShot Forge" },
    { name: "Silkshot (Twelfth Architect)", location: "478732", saveName: "WebShot Architect" },
    { name: "Silkshot (Mount Fay)", location: "479497", saveName: "WebShot Weaver" },
    { name: "Delver's Drill", location: "478577", saveName: "Screw Attack" },
    { name: "Cogwork Wheel", location: "478725", saveName: "Cogwork Saw" },
    { name: "Cogfly", location: "478903", saveName: "Cogwork Flier" },
    { name: "Rosary Cannon", location: "478937", saveName: "Rosary Cannon" },
    { name: "Flintslate", location: "477986", saveName: "Flintstone" },
    { name: "Snare Setter", location: "479071", saveName: "Silk Snare" },
    { name: "Flea Brew", location: "478025", saveName: "Flea Brew" },
    { name: "Plasmium Phial", location: "478496", saveName: "Lifeblood Syringe" },
    { name: "Needle Phial", location: "478482", saveName: "Extractor" },
    { name: "Voltvessels", location: "479121", saveName: "Lightning Rod" },
    // blue tools
    { name: "Druid's Eye", location: "478255", saveName: "Mosscreep Tool 1" },
    { name: "Druid's Eyes", location: "480493", saveName: "Mosscreep Tool 2" },
    { name: "Magma Bell", location: "477918", saveName: "Lava Charm" },
    { name: "Warding Bell", location: "477935", saveName: "Bell Bind" },
    { name: "Pollip Pouch", location: "478294", saveName: "Poison Pouch" },
    { name: "Fractured Mask", location: "478607", saveName: "Fractured Mask" },
    { name: "Multibinder", location: "478345", saveName: "Multibind" },
    { name: "Weavelight", location: "479070", saveName: "White Ring" },
    { name: "Sawtooth Circlet", location: "478726", saveName: "Brolly Spike" },
    { name: "Injector Band", location: "479182", saveName: "Quickbind" },
    { name: "Spool Extender", location: "478881", saveName: "Spool Extender" },
    { name: "Resserve Bind", location: "479254", saveName: "Reserve Bind" },
    { name: "Claw Mirror", location: "478691", saveName: "Dazzle Bind" },
    { name: "Claw Mirrors", location: "479378", saveName: "Dazzle Bind Upgraded" },
    { name: "Memory Crystal", location: "478947", saveName: "Revenge Crystal" },
    { name: "Snitch Pick", location: "479201", saveName: "Thief Claw" },
    { name: "Volt Filament", location: "479224", saveName: "Zap Imbuement" },
    { name: "Quick Sling", location: "478848", saveName: "Quick Sling" },
    { name: "Wreath of Purity", location: "479133", saveName: "Maggot Charm" },
    { name: "Longclaw", location: "479240", saveName: "Longneedle" },
    { name: "Wispfire Lantern", location: "479156", saveName: "Wisp Lantern" },
    { name: "Egg of Flealia", location: "479439", saveName: "Flea Charm" },
    { name: "Pin Badge", location: "479466", saveName: "Pinstress Tool" },
    // yellow tools
    { name: "Compass", location: "477851", saveName: "Compass" },
    { name: "Shard Pendant", location: "477848", saveName: "Bone Necklace" },
    { name: "Magnetite Brooch", location: "477841", saveName: "Rosary Magnet" },
    { name: "Weighted Belt", location: "477947", saveName: "Weighted Anklet" },
    { name: "Barbed Bracelet", location: "478341", saveName: "Barbed Wire" },
    { name: "Dead Bug's Purse", location: "479081", saveName: "Dead Mans Purse" },
    { name: "Shell Satchel", location: "479996", saveName: "Shell Satchel" },
    { name: "Magnetite Dice", location: "479309", saveName: "Magnetite Dice" },
    { name: "Scuttlebrace", location: "478727", saveName: "Scuttlebrace" },
    { name: "Ascendant's Grip", location: "478878", saveName: "Wallcling" },
    { name: "Spider Strings", location: "479248", saveName: "Musician Charm" },
    { name: "Silkspeed Anklets", location: "478216", saveName: "Sprintmaster" },
    { name: "Thief's Mark", location: "478525", saveName: "Thief Charm" },
]

export const bellwayStationList = [
    { name: "Bone Bottom", location: "477883", flag: "UnlockedFastTravel" },
    { name: "The Marrow", location: "477882", flag: "UnlockedFastTravel" },
    { name: "Deep Docks", location: "477905", flag: "UnlockedDocksStation" },
    { name: "Far Fields", location: "477933", flag: "UnlockedBoneforestEastStation" },
    { name: "Greymoor", location: "478037", flag: "UnlockedGreymoorStation" },
    { name: "Bellhart", location: "478029", flag: "UnlockedBelltownStation" },
    { name: "Shellwood", location: "478178", flag: "UnlockedShellwoodStation" },
    { name: "Blasted Steps", location: "478308", flag: "UnlockedCoralTowerStation" },
    { name: "The Slab", location: "478390", flag: "UnlockedPeakStation" },
    { name: "Grand Bellway", location: "478374", flag: "UnlockedCityStation" },
    { name: "Bilewater", location: "478447", flag: "UnlockedShadowStation" },
    { name: "Putrified Ducts", location: "478411", flag: "UnlockedAqueductStation" },
];

export const ventricaStationList = [
    { name: "Terminus", location: "478426", flag: ["UnlockedArboriumTube", "UnlockedHangTube", "UnlockedSongTube", "UnlockedCityBellwayTube", "UnlockedUnderTube"] },
    { name: "Memorium", location: "478425", flag: "UnlockedArboriumTube" },
    { name: "High Halls", location: "478445", flag: "UnlockedHangTube" },
    { name: "First Shrine", location: "478427", flag: "UnlockedArboriumTube" },
    { name: "Choral Chambers", location: "478424", flag: "UnlockedSongTube" },
    { name: "Grand Bellway", location: "478376", flag: "UnlockedCityBellwayTube" },
    { name: "Underworks", location: "478422", flag: "UnlockedUnderTube" },
];


export const toolPouchList = [ // wip
    { name: "Tool Pouch #1", location: "477950", flag: "PurchasedPilgrimsRestToolPouch", flagType: "purchase" },
    { name: "Tool Pouch #2 (WIP)", location: "478252", flag: "Bone_12", flagType: "scene" },
    { name: "Tool Pouch #3", location: "479167", flag: "Journal", flagType: "quest" },
    { name: "Tool Pouch #4", location: "479436", flag: "FleasCollectedTargetOrder", flagType: "flea" }, // look at fleas collected target order
]

export const craftingKitUpgradeList = [
    { name: "Crafting Kit #1", location: "477919", flag: "PurchasedForgeToolKit", flagType: "purchase" },
    { name: "Crafting Kit #2", location: "478348", flag: "Crow Feathers", flagType: "quest" },
    { name: "Crafting Kit #3", location: "478728", flag: "PurchasedArchitectToolKit", flagType: "purchase" },
    { name: "Crafting Kit #4", location: "478533", flag: "purchasedGrindleToolKit", flagType: "purchase" },
];

export const memoryLocketList = [
    { name: "#1 Moss Grotto", location: "478222", flag: "Rock Rollers", flagType: "quest" },
    { name: "#2 The Marrow", location: "478246", flag: "Bone_18", flagType: "scene" }, // Collectable Item Pickup
    { name: "#3 Far Fields (1/2)", location: "477953", flag: "PurchasedPilgrimsRestMemoryLocket", flagType: "boolean" },
    { name: "#4 Far Fields (2/2)", location: "479196", flag: "Bone_East_25", flagType: "scene" },
    { name: "#5 Greymoor (1/2)", location: "478035", flag: "Greymoor_16", flagType: "scene" },
    { name: "#6 Greymoor (2/2)", location: "478039", flag: "Halfway_01", flagType: "scene" },
    { name: "#7 Hunter's March", location: "478017", flag: "Ant_20", flagType: "scene" },
    { name: "#8 Bellhart (1/2)", location: "478204", flag: "PurchasedBelltownMemoryLocket", flagType: "boolean" },
    { name: "#9 Bellhart (2/2)", location: "478212", flag: "Belltown", flagType: "scene" },
    { name: "#10 Blasted Steps", location: "478502", flag: "Coral_02", flagType: "scene" }, // Collectable Item Pickup (1)
    { name: "#11 Wormways", location: "478493", flag: "Crawl_09", flagType: "scene" },
    { name: "#12 The Slab", location: "479017", flag: "Slab_Cell_Quiet", flagType: "scene" },
    { name: "#13 Sands of Karak", location: "479204", flag: "Coral_23", flagType: "scene" },
    { name: "#14 Memorium", location: "479110", flag: "Arborium_05", flagType: "scene" },
    { name: "#15 Bilewater (1/2)", location: "478787", flag: "Shadow_20", flagType: "scene" }, // Collectable Item Pickup (1) OR Collectable Item Pickup
    { name: "#16 Bilewater (2/2)", location: "478851", flag: "Shadow_27", flagType: "scene" }, // Sack Corpse Pickup
    { name: "#17 Whispering Vaults", location: "478676", flag: "Library_08", flagType: "scene" },
    { name: "#18 Underworks", location: "478571", flag: "Under_08", flagType: "scene" },
    { name: "#19 Deep Docks", location: "478836", flag: "Dock_13", flagType: "scene" },
    { name: "#20 Choral Chambers", location: "478372", flag: "Bellway_City", flagType: "scene" },
];

export const simpleKeysList = [
    { name: "#1 Bone Bottom", location: "477839", flag: "PurchasedBonebottomFaithToken", flagType: "boolean" }, //true
    { name: "#2 Choral Chambers", location: "478880", flag: "MerchantEnclaveSimpleKey", flagType: "boolean" }, // true
    { name: "#3 Sinner's Road", location: "478280", flag: "Dust_06", flagType: "scene" }, // ID is Collectable Item SimpleKey
    { name: "#4 Sands of Karak", location: "479215", flag: "Bellshrine_Coral", flagType: "scene" } // ID is Collectable Item Pickup
];

export const keyList = [
    { name: "Key of Indolent", location: "478467", flag: "HasSlabKeyA", flagType: "boolean" },
    { name: "Key of Heretic", location: "478474", flag: "HasSlabKeyB", flagType: "boolean" },
    { name: "Key of Apostate", location: "478963", flag: "HasSlabKeyC", flagType: "boolean" },
    { name: "Architect's Key", location: "478729", flag: "PurchasedArchitectKey", flagType: "boolean" },
    { name: "Diving Bell Key", location: "479279", flag: "BallowGivenKey", flagType: "boolean" },
    { name: "White Key", location: "478599", flag: ["collectedWardKey", "MerchantEnclaveWardKey"], flagType: "multi" },
    { name: "Surgeon's Key", location: "478923", flag: "collectedWardBossKey", flagType: "boolean" },
];

export const mementoList = [
    { name: "Grey Memento", location: "479630", flag: "Grey Memento", flagType: "deposit" },
    { name: "Hero's Memento", location: "479632", flag: "Memento Garmond", flagType: "deposit" },
    { name: "Surface Memento", location: "479542", flag: "Memento Surface", flagType: "deposit" },
    { name: "Hunter's Memento", location: "479635", flag: "Hunter Memento", flagType: "deposit" },
    { name: "Craw Memento", location: "479580", flag: "Crowman Memento", flagType: "deposit" },
    { name: "Sprintmaster Memento", location: "479634", flag: "Sprintmaster Memento", flagType: "deposit" },
    { name: "Guardian's Memento", location: "479638", flag: "FleaGamesMementoGiven", flagType: "boolean" },
];

export const heartList = [
    { name: "Conjoined Heart", location: "479631", flag: "defeatedCloverDancers" },
    { name: "Hunter's Heart", location: "481832", flag: "defeatedAntQueen" },
    { name: "Pollen Heart", location: "479404", flag: "defeatedFlowerQueen" },
    { name: "Encrusted Heart", location: "479392", flag: "defeatedCoralKing" },
]

export const runeHarpList = [
    { name: "#1 Weavenest Atla" , location: "478231", flag: "Weaver Record Weave_08" },
    { name: "#2 High Halls", location: "479495", flag: "Weaver Record Conductor" },
    { name: "#3 Far Fields", location: "479057", flag: "Weaver Record Sprint_Challenge" },
];

export const boneScrollList = [
    { name: "#1 Greymoor", location: "478142", flag: "Bone Record Greymoor_flooded_corridor" },
    { name: "#2 Underworks", location: "478553", flag: "Bone Record Understore_Map_Room" },
    { name: "#3 Wisp Thicket", location: "479150", flag: "Bone Record Wisp Top" },
    { name: "#4 Far Fields", location: "478213", flag: "Bone Record Greymoor_flooded_corridor" },
];

export const choralCommandmentList = [
    { name: "#1 Whiteward (1/2)", location: "478914", flag: "Seal Chit Ward Corpse" },
    { name: "#2 Whiteward (2/2)", location: "478919", flag: "Seal Chit Silk Siphon" },
    { name: "#3 Songclave", location: "479251", flag: "Seal Chit City Merchant" },
    { name: "#4 Bone Bottom", location: "477867", flag: "Seal Chit Aspid_01" },
];

export const weaverEffigyList = [
    { name: "#1 The Slab", location: "479034", flag: "Weaver Totem Slab_Bottom" },
    { name: "#2 Bone Bottom", location: "478093", flag: "Weaver Totem Bonetown_upper_room" },
    { name: "#3 Shellwood", location: "478794", flag: "Weaver Totem Witch" },
];

export const psalmCylinderList = [ // isCollected
    { name: "#1 Blasted Steps", location: "478530", flag: "Psalm Cylinder Grindle" },
    { name: "#2 Whispering Vaults (1/3)", location: "478774", flag: "Psalm Cylinder Library Roof" },
    { name: "#3 Whispering Vaults (2/3)", location: "478650", flag: "Psalm Cylinder Librarian"},
    { name: "#4 Whispering Vaults (3/3)", location: "479717", flag: "Librarian Melody Cylinder" },
    { name: "#5 High Halls", location: "478908", flag: "Psalm Cylinder Hang" },
    { name: "#6 Underworks", location: "478929", flag: "Psalm Cylinder Ward"  },
];

export const spoolFragmentList = [
    { name: "#1 Moss Grotto", location: "478080", flag: "Bone_11b", flagType: "scene" },
    { name: "#2 Deep Docks (1/2)", location: "477926", flag: "Bone_East_13", flagType: "scene" },
    { name: "#3 Deep Docks (2/2)", location: "478825", flag: "Dock_03c", flagType: "scene" },
    { name: "#4 Choral Chambers", location: "479249", flag: "MerchantEnclaveSpoolPiece", flagType: "boolean" },
    { name: "#5 Greymoor (2/2)", location: "478263", flag: "Greymoor_02", flagType: "scene" },
    { name: "#6 Bellhart", location: "478347", flag: "PurchasedBelltownSpoolSegment", flagType: "boolean" },
    { name: "#7 Weavenest Atla", location: "478230", flag: "Weave_11", flagType: "scene" },
    { name: "#8 The Slab", location: "478475", flag: "Peak_01", flagType: "scene" },
    { name: "#9 Underworks (1/2)", location: "478931", flag: "Library_11b", flagType: "scene" },
    { name: "#10 Underworks (2/2)", location: "478704", flag: "Under_10", flagType: "scene" },
    { name: "#11 Grand Gate", location: "478586", flag: "Song_19_entrance", flagType: "scene" },
    { name: "#12 Memorium", location: "479117", flag: "Arborium_09", flagType: "scene" },
    { name: "#13 Whiteward (1/2)", location: "479317", flag: "Ward_01", flagType: "scene" },
    { name: "#14 Whiteward (2/2)", location: "479180", flag: "Save Sherma", flagType: "quest" },
    { name: "#15 Blasted Steps (1/2)", location: "478527", flag: "purchasedGrindleSpoolPiece", flagType: "boolean" },
    { name: "#16 Blasted Steps (2/2)", location: "478820", flag: "MetCaravanTroupeLeaderJudge", flagType: "boolean" },
    { name: "#17 High Halls", location: "478909", flag: "Hang_03_top", flagType: "scene" },
    { name: "#18 Cogwork Core", location: "478618", flag: "Cog_07", flagType: "scene" },
];

export const objectiveList = [
    { name: "The Great Citadel", location: "477834", saveName: "Citadel Seeker", flagType: "quest" },
    { name: "The Threadspun Town", location: "478028", saveName: "The Threadspun Town", flagType: "quest" },
    { name: "Grand Gate", location: "478544", saveName: "Grand Gate Bellshrines", flagType: "quest" },
    { name: "Silent Halls", location: "478547", saveName: "Citadel Investigate", flagType: "quest" },
    { name: "Pharloom's Crown", location: "479087", saveName: "Citadel Ascent", flagType: "quest" },
    { name: "Conductor's Melody", location: "478609", saveName: "HasMelodyConductor", flagType: "boolean" },
    { name: "Architect's Melody", location: "478610", saveName: "HasMelodyArchitect", flagType: "boolean" },
    { name: "Vaultkeeper's Melody", location: "478611", saveName: "HasMelodyLibrarian", flagType: "boolean" },
    { name: "Pale Monarch", location: "479100", saveName: "Silk Defeat Snare", flagType: "quest" },
    { name: "Soul Snare", location: "479260", saveName: "Soul Snare", flagType: "quest" },
    { name: "Beast in the Bells", location: "479263", saveName: "Bellbeast Rescue", flagType: "quest" },
    { name: "After the Fall", location: "479261", saveName: "Black Thread Pt0", flagType: "quest" },
    { name: "Awaiting the End", location: "479262", saveName: "Black Thread Pt1 Shamans", flagType: "quest" },
    { name: "The Dark Below", location: "479267", saveName: "Diving Bell Pt3 Descend", flagType: "quest" },
    { name: "Return to Pharloom", location: "479283", saveName: "Black Thread Pt3 Escape", flagType: "quest" },
    { name: "Spell Seeker", location: "479385", saveName: "Black Thread Pt4 Return", flagType: "quest" },
    { name: "The Old Hearts", location: "479387", saveName: "Black Thread Pt5 Heart", flagType: "quest" },
    { name: "Heart of Might", location: "479388", saveName: "CollectedHeartCoral", flagType: "boolean" },
    { name: "Heart of the Woods", location: "479389", saveName: "CollectedHeartFlower", flagType: "boolean" },
    { name: "Heart of the Wild", location: "479390", saveName: "CollectedHeartHunter", flagType: "boolean" },
    { name: "Last Dive", location: "479431", saveName: "Lost Lace", flagType: "journal" },
];

export const questList = [
    { name: "Bone Bottom Repairs", location: "477884", saveName: "Building Materials" },
    { name: "Garb of the Pilgrims", location: "477885", saveName: "Pilgrim Rags" },
    { name: "A Lifesaving Bridge", location: "478220", saveName: "Building Materials (Bridge)" },
    { name: "Volatile Flintbeetles", location: "478221", saveName: "Rock Rollers" },
    { name: "An Icon of Hope", location: "478839", saveName: "Building Materials (Statue)" },
    { name: "The Lost Fleas", location: "477857", saveName: "Save the Fleas" },
    { name: "Flexile Spines", location: "477964", saveName: "Brolly Get" },
    { name: "Fastest in Pharloom", location: "479193", saveName: "Sprintmaster Race" },
    { name: "Berry Picking", location: "477876", saveName: "Mossberry Collection 1" },
    { name: "Bugs of Pharloom", location: "478042", saveName: "Journal" },
    { name: "Rite of the Pollip", location: "478173", saveName: "Shell Flowers" },
    { name: "Silver Bells", location: "478314", saveName: "Shiny Bell Goomba" },
    { name: "My Missing Courier", location: "478207", saveName: "Save Courier Short" },
    { name: "Crawbug Clearing", location: "478348", saveName: "Crow Feathers" },
    { name: "Pinmaster's Oil", location: "478211", saveName: "A Pinsmiths Tools" },
    { name: "The Terrible Tyrant", location: "478223", saveName: "Skull King" },
    { name: "Restoration of Bellhart", location: "478797", saveName: "Belltown House Start" },
    { name: "Bellhart's Glory", location: "478797", saveName: "Belltown House Mid" },
    { name: "Great Taste of Pharloom", location: "478889", saveName: "Great Gourmand" },
    { name: "Building up Songclave", location: "478631s", saveName: "Songclave Donation 1" },
    { name: "Fine Pins", location: "478633", saveName: "Fine Pins" },
    { name: "The Wandering Merchant", location: "478634", saveName: "Save City Merchant" },
    { name: "The Lost Merchant", location: "479244", saveName: "Save City Merchant Bridge" },
    { name: "My Missing Courier", location: "478207", saveName: "Save Courier Short" },
    { name: "My Missing Brother", location: "478798", saveName: "Save Courier Tall" },
    { name: "Balm for the Wounded", location: "478933", saveName: "Save Sherma" },
    { name: "Savage Beastfly", location: "478799", saveName: "Beastfly Hunt" },
    { name: "Cloaks of the Choir", location: "478934", saveName: "Song Pilgrim Cloaks" },
    { name: "Strengthening Songclave", location: "479239", saveName: "Songclave Donation 2" },
    { name: "The Wailing Mother", location: "479246", saveName: "Broodmother Hunt" },
    { name: "Broodfeast", location: "478865", saveName: "Huntress Quest" },
    { name: "Trail's End", location: "479237", saveName: "Shakra Final Quest" },
    { name: "Rite of Rebirth", location: "478792", saveName: "Wood Witch Curse" },
    { name: "Infestation Operation", location: "478814", saveName: "Doctor Curse Cure" },
    { name: "Silk and Soul", location: "479243", saveName: "Soul Snare Pre" },
    { name: "Dark Hearts", location: "479448", saveName: "Destroy Thread Cores" },
    { name: "Pain, Anguish, and Misery", location: "479370", saveName: "Tormented Trobbio" },
    { name: "Fatal Resolve", location: "479465", saveName: "Pinstress Battle" },
    { name: "Ecstasy of the End", location: "479641", saveName: "Flea Games" },
    { name: "Passing of the Age", location: "479142", saveName: "Mr Mushroom" },
    { name: "Alchemist's Assistant", location: "478482", saveName: "Extractor Blue" },
    { name: "Advanced Alchemy", location: "479278", saveName: "Extractor Blue Worms" },
    { name: "The Hidden Hunter", location: "479446", saveName: "Ant Trapper" },
    { name: "Hero's Call", location: "479445", saveName: "Garmond Black Threaded" },
    { name: "Final Audience", location: "479245", saveName: "Song Knight" },
    { name: "Roach Guts", location: "478356", saveName: "Roach Killing" },
    { name: "Bone Bottom Supplies", location: "478313", saveName: "Courier Delivery Bonebottom" },
    { name: "Fleatopia Supplies", location: "478313", saveName: "Courier Delivery Fleatopia" },
    { name: "Songclave Supplies", location: "478313", saveName: "Courier Delivery Songclave" },
    { name: "Liquid Lacquer", location: "479199", saveName: "Courier Delivery Mask Maker" },
    { name: "Pilgrim's Rest Supplies", location: "478313", saveName: "Courier Delivery Pilgrims Rest" },
    { name: "Queen's Egg", location: "479177", saveName: "Courier Delivery Dustpens Slave" },
    { name: "A Vassal Lost", location: "479727", saveName: "Steel Sentinel Pt2" },
];

export const maskShardList = [
    { name: "#1 Moss Grotto", location: "477840", flag: "PurchasedBonebottomHeartPiece", flagType: "boolean" },
    { name: "#2 Far Fields (1/3)", location: "477975", flag: "Bone_East_20", flagType: "scene" },
    { name: "#3 Far Fields (2/3)", location: "478841", flag: "Bone_East_LavaChallenge", flagType: "scene" }, // Heart piece (1)
    { name: "#4 Far Fields (3/3)", location: "479194", flag: "Sprintmaster Race", flagType: "quest" },
    { name: "#5 Deep Docks", location: "477901", flag: "Dock_08", flagType: "scene" },
    { name: "#6 Wormways", location: "478091", flag: "Crawl_02", flagType: "scene" },
    { name: "#7 Bellhart (1/3)", location: "478800", flag: "Beastfly Hunt", flagType: "quest" },
    { name: "#8 Bellhart (2/3)", location: "479447", flag: "Ant Trapper", flagType: "quest" },
    { name: "#9 Bellhart (3/3)", location: "479449", flag: "Destroy Thread Cores", flagType: "quest" },
    { name: "#10 Shellwood", location: "478177", flag: "Shellwood_14", flagType: "scene" },
    { name: "#11 Weavenest Atla", location: "478233", flag: "Weave_05b", flagType: "scene" },
    { name: "#12 Blasted Steps", location: "478498", flag: "Coral_19b", flagType: "scene" },
    { name: "#13 Choral Chambers", location: "478879", flag: "MerchantEnclaveSocket", flagType: "boolean" },
    { name: "#14 Cogwork Core", location: "478615", flag: "Song_09", flagType: "scene" },
    { name: "#15 The Slab", location: "479001", flag: "Slab_17", flagType: "scene" },
    { name: "#16 Mount Fay (1/2)", location: "479038", flag: "Peak_04c", flagType: "scene" },
    { name: "#17 Mount Fay (2/2)", location: "479460", flag: "Peak_06", flagType: "scene" },
    { name: "#18 Whispering Vaults", location: "478671", flag: "Library_05", flagType: "scene" },
    { name: "#19 Bilewater", location: "478849", flag: "Shadow_13", flagType: "scene" },
    { name: "#20 Wisp Thicket", location: "479151", flag: "Wisp_07", flagType: "scene" },
];

export const paleOilList = [
    { name: "Pale Oil #1", location: "478668", flag: "Library_03", flagType: "scene" },
    { name: "Pale Oil #2", location: "478889", flag: "Great Gourmand", flagType: "quest" },
    { name: "Pale Oil #3", location: "479444", flag: "Flea Games", flagType: "quest" },
];

export const fleaList = [
    { name: "#1 The Marrow", location: "477890", flag: "SavedFlea_Bone_06", flagType: "boolean" },
    { name: "#2 Deep Docks (1/3)", location: "477907", flag: "SavedFlea_Dock_16", flagType: "boolean" },
    { name: "#3 Deep Docks (2/3)", location: "477916", flag: "SavedFlea_Bone_East_05", flagType: "boolean" },
    { name: "#4 Deep Docks (3/3)", location: "478437", flag: "SavedFlea_Dock_03d", flagType: "boolean" },
    { name: "#5 Far Fields (1/2)", location: "477940", flag: "SavedFlea_Bone_East_17b", flagType: "boolean" },
    { name: "#6 Far Fields (2/2)", location: "478219", flag: "SavedFlea_Bone_East_10_Church", flagType: "boolean" },
    { name: "#7 Hunters March", location: "477999", flag: "SavedFlea_Ant_03", flagType: "boolean" },
    { name: "#8 Greymoor (1/2)", location: "478145", flag: "SavedFlea_Greymoor_15b", flagType: "boolean" },
    { name: "#9 Greymoor (2/2)", location: "478287", flag: "SavedFlea_Greymoor_06", flagType: "boolean" },
    { name: "#10 Sinner's Road", location: "478360", flag: "SavedFlea_Dust_12", flagType: "boolean" },
    { name: "#11 Whispering Vaults", location: "478402", flag: "SavedFlea_Library_01", flagType: "boolean" },
    { name: "#12 Bilewater (1/3)", location: "478378", flag: "SavedFlea_Dust_09", flagType: "boolean" },
    { name: "#13 Bilewater (2/3)", location: "478408", flag: "SavedFlea_Shadow_10", flagType: "boolean" },
    { name: "#14 Bilewater (3/3)", location: "478443", flag: "SavedFlea_Shadow_28", flagType: "boolean" },
    { name: "#15 Underworks (1/2)", location: "478420", flag: "SavedFlea_Under_21", flagType: "boolean" },
    { name: "#16 Underworks (2/2)", location: "478419", flag: "SavedFlea_Under_23", flagType: "boolean" },
    { name: "#17 Blasted Steps", location: "478386", flag: "SavedFlea_Coral_35", flagType: "boolean" },
    { name: "#18 Bellhart", location: "478193", flag: "SavedFlea_Belltown_04", flagType: "boolean" },
    { name: "#19 Wormways", location: "478450", flag: "SavedFlea_Crawl_06", flagType: "boolean" },
    { name: "#20 Coral Chambers (1/2)", location: "478416", flag: "SavedFlea_Song_11", flagType: "boolean" },
    { name: "#21 Coral Chambers (2/2)", location: "478398", flag: "SavedFlea_Song_14", flagType: "boolean" },
    { name: "#22 The Slab (1/2)", location: "478393", flag: "SavedFlea_Slab_Cell", flagType: "boolean" },
    { name: "#23 The Slab (2/2)", location: "478392", flag: "SavedFlea_Slab_06", flagType: "boolean" },
    { name: "#24 Mount Fay", location: "478380", flag: "SavedFlea_Peak_05c", flagType: "boolean" },
    { name: "#25 Songclave", location: "478404", flag: "SavedFlea_Library_09", flagType: "boolean" },
    { name: "#26 Sands of Karak", location: "478385", flag: "SavedFlea_Coral_24", flagType: "boolean" },
    { name: "#27 Shellwood", location: "478176", flag: "SavedFlea_Shellwood_03", flagType: "boolean" },
    { name: "#28 Memorium", location: "478413", flag: "tamedGiantFlea", flagType: "boolean" },
    { name: "#29 Kratt NPC", location: "478271", flag: "Greymoor_24", flagType: "scene" }, // NPC Value two
    { name: "#30 Vog NPC", location: "479138", flag: "GLOBAL_SHARED", flagType: "scene" }, // ID Caravan Troupe Hunter
];

export const craftMetalList = [
    { name: "#1 Moss Grotto", location: "477838", flag: "PurchasedBonebottomToolMetal", flagType: "purchase" },
    { name: "#2 The Marrow", location: "477894", flag: "Bone_07", flagType: "scene" }, // tool_metal_deposit
    { name: "#3 Deep Docks", location: "477937", flag: "CollectedToolMetal", flagType: "purchase" },
    { name: "#4 Blasted Steps", location: "478541", flag: "Coral_32", flagType: "scene" },
    { name: "#5 Songclave", location: "479250", flag: "MerchantEnclaveToolMetal", flagType: "purchase" },
    { name: "#6 Underworks", location: "478711", flag: "Under_19b", flagType: "scene" },
    { name: "#7 Putrified Ducts", location: "479139", flag: "Aqueduct_05", flagType: "scene" },
    { name: "#8 Wisp Thicket", location: "479157", flag: "Wisp_05", flagType: "scene" },
];


export const journalEntryList = [
    { name: 'Mossgrub', requiredKillCount: 25, saveName: 'MossBone Crawler', location: '479075' },
    { name: 'Massive Mossgrub', requiredKillCount: 3, saveName: 'MossBone Crawler Fat', location: '480252' },
    { name: 'Mossmir', requiredKillCount: 20, saveName: 'MossBone Fly', location: '479076' },
    { name: 'Moss Mother', requiredKillCount: 3, saveName: 'Mossbone Mother', location: '480309' },
    { name: 'Aknid', requiredKillCount: 15, saveName: 'Aspid Collector', location: '479579' },
    { name: 'Skull Scuttler', requiredKillCount: 35, saveName: 'Bone Goomba', location: '479543' },
    { name: 'Skullwing', requiredKillCount: 15, saveName: 'Bone Goomba Bounce Fly', location: '479543' },
    { name: 'Skull Brute', requiredKillCount: 15, saveName: 'Bone Goomba Large', location: '479546' },
    { name: 'Skull Tyrant', requiredKillCount: 1, saveName: 'Skull King', location: '480313' },
    { name: 'Kilik', requiredKillCount: 25, saveName: 'Bone Crawler', location: '479550' },
    { name: 'Beastfly', requiredKillCount: 30, saveName: 'Bone Flyer', location: '479544' },
    { name: 'Savage Beastfly', requiredKillCount: 2, saveName: 'Bone Flyer Giant', location: '480317' },
    { name: 'Caranid', requiredKillCount: 25, saveName: 'Bone Circler', location: '479547' },
    { name: 'Vicious Caranid', requiredKillCount: 15, saveName: 'Bone Circler Vicious', location: '479564' },
    { name: 'Hardbone Hopper', requiredKillCount: 20, saveName: 'Bone Hopper', location: '479555' },
    { name: 'Hardbone Elder', requiredKillCount: 10, saveName: 'Bone Hopper Giant', location: '480213' },
    { name: 'Tarmite', requiredKillCount: 10, saveName: 'Bone Spitter', location: '479058' },
    { name: 'Mawling', requiredKillCount: 30, saveName: 'Bone Roller', location: '479077' },
    { name: 'Marrowmaw', requiredKillCount: 8, saveName: 'Bone Thumper', location: '478224' },
    { name: 'Hoker', requiredKillCount: 15, saveName: 'Spine Floater', location: '479570' },
    { name: 'Flintbeetle', requiredKillCount: 3, saveName: 'Rock Roller', location: '478248' },
    { name: 'Rhinogrund', requiredKillCount: 2, saveName: 'Rhino', location: '480179' },
    { name: 'Gromling', requiredKillCount: 25, saveName: 'Crypt Worm', location: '479078' },
    { name: 'Grom', requiredKillCount: 10, saveName: 'Bone Worm', location: '479080' },
    { name: 'Bell Beast', requiredKillCount: 1, saveName: 'Bone Beast', location: '480312' },
    { name: 'Pilgrim Groveller', requiredKillCount: 35, saveName: 'Pilgrim 03', location: '479571' },
    { name: 'Pilgrim Pouncer', requiredKillCount: 35, saveName: 'Pilgrim 01', location: '479551' },
    { name: 'Pilgrim Hornfly', requiredKillCount: 15, saveName: 'Pilgrim 04', location: '479573' },
    { name: 'Pilgrim Hulk', requiredKillCount: 10, saveName: 'Pilgrim 02', location: '479574' },
    { name: 'Pilgrim Bellbearer', requiredKillCount: 10, saveName: 'Pilgrim Bell Thrower', location: '478044' },
    { name: 'Winged Pilgrim', requiredKillCount: 25, saveName: 'Pilgrim Fly', location: '479552' },
    { name: 'Elder Pilgrim', requiredKillCount: 5, saveName: 'Pilgrim 05', location: '479755' },
    { name: 'Winged Pilgrim Bellbearer', requiredKillCount: 10, saveName: 'Pilgrim Bellthrower Fly', location: '478301' },
    { name: 'Pilgrim Hiker', requiredKillCount: 10, saveName: 'Pilgrim Hiker', location: '479738' },
    { name: 'Pilgrim Guide', requiredKillCount: 15, saveName: 'Pilgrim StaffWielder', location: '479683' },
    { name: 'Overgrown Pilgrim', requiredKillCount: 20, saveName: 'Pilgrim Moss Spitter', location: '479577' },
    { name: 'Covetous Pilgrim', requiredKillCount: 2, saveName: 'Rosary Pilgrim', location: '478300' },
    { name: 'Snitchfly', requiredKillCount: 4, saveName: 'Rosary Thief', location: '479000' },
    { name: 'Lavalug', requiredKillCount: 12, saveName: 'Tar Slug', location: '479565' },
    { name: 'Lavalarga', requiredKillCount: 8, saveName: 'Tar Slug Huge', location: '480236' },
    { name: 'Smelt Shoveller', requiredKillCount: 25, saveName: 'Dock Worker', location: '479553' },
    { name: 'Flintstone Flyer', requiredKillCount: 25, saveName: 'Dock Flyer', location: '479554' },
    { name: 'Flintflame Flyer', requiredKillCount: 10, saveName: 'Dock Bomber', location: '479566' },
    { name: 'Smokerock Sifter', requiredKillCount: 10, saveName: 'Shield Dock Worker', location: '479567' },
    { name: 'Deep Diver', requiredKillCount: 5, saveName: 'Dock Charger', location: '480237' },
    { name: 'Forebrothers Signis & Gron', requiredKillCount: 1, saveName: 'Dock Guard Thrower', location: '480314' },
    { name: 'Cragglite', requiredKillCount: 3, saveName: 'Small Crab', location: '480145' },
    { name: 'Craggler', requiredKillCount: 1, saveName: 'Roof Crab', location: '478088' },
    { name: 'Brushflit', requiredKillCount: 15, saveName: 'Fields Flock Flyers', location: '479560' },
    { name: 'Fertid', requiredKillCount: 25, saveName: 'Fields Goomba', location: '479561' },
    { name: 'Flapping Fertid', requiredKillCount: 20, saveName: 'Fields Flyer', location: '479562' },
    { name: 'Fourth Chorus', requiredKillCount: 1, saveName: 'Song Golem', location: '480315' },
    { name: 'Skarrlid', requiredKillCount: 25, saveName: 'Bone Hunter Tiny', location: '479558' },
    { name: 'Skarrwing', requiredKillCount: 30, saveName: 'Bone Hunter Buzzer', location: '479557' },
    { name: 'Skarr Scout', requiredKillCount: 20, saveName: 'Bone Hunter Child', location: '479559' },
    { name: 'Skarr Stalker', requiredKillCount: 15, saveName: 'Bone Hunter', location: '479563' },
    { name: 'Spear Skarr', requiredKillCount: 10, saveName: 'Bone Hunter Fly', location: '479591' },
    { name: 'Skarrgard', requiredKillCount: 2, saveName: 'Bone Hunter Throw', location: '477962' },
    { name: 'Gurr the Outcast', requiredKillCount: 1, saveName: 'Bone Hunter Trapper', location: '480316' },
    { name: 'Last Claw', requiredKillCount: 6, saveName: 'Bone Hunter Chief', location: '480483' },
    { name: 'Skarrsinger Karmelita', requiredKillCount: 1, saveName: 'Hunter Queen', location: '479198' },
    { name: 'Mite', requiredKillCount: 30, saveName: 'Mite', location: '479681' },
    { name: 'Fluttermite', requiredKillCount: 25, saveName: 'Mitefly', location: '478974' },
    { name: 'Mitemother', requiredKillCount: 10, saveName: 'Gnat Giant', location: '478975' },
    { name: 'Dreg Catcher', requiredKillCount: 20, saveName: 'Farmer Catcher', location: '479685' },
    { name: 'Silk Snipper', requiredKillCount: 25, saveName: 'Farmer Scissors', location: '478150' },
    { name: 'Thread Raker', requiredKillCount: 15, saveName: 'Farmer Centipede', location: '478979' },
    { name: 'Moorwing', requiredKillCount: 1, saveName: 'Vampire Gnat', location: '480340' },
    { name: 'Wisp', requiredKillCount: 15, saveName: 'Wisp', location: '480438' },
    { name: 'Burning Bug', requiredKillCount: 8, saveName: 'Farmer Wisp', location: '480440' },
    { name: 'Father of the Flame', requiredKillCount: 1, saveName: 'Wisp Pyre Effigy', location: '480349' },
    { name: 'Craw', requiredKillCount: 25, saveName: 'Crow', location: '479679' },
    { name: 'Tallcraw', requiredKillCount: 20, saveName: 'Crowman', location: '479680' },
    { name: 'Squatcraw', requiredKillCount: 15, saveName: 'Crowman Dagger', location: '479682' },
    { name: 'Craw Juror', requiredKillCount: 15, saveName: 'Crowman Juror Tiny', location: '480485' },
    { name: 'Tallcraw Juror', requiredKillCount: 10, saveName: 'Crowman Juror', location: '480486' },
    { name: 'Squatcraw Juror', requiredKillCount: 8, saveName: 'Crowman Dagger Juror', location: '480487' },
    { name: 'Crawfather', requiredKillCount: 1, saveName: 'Crawfather', location: '480319' },
    { name: 'Muckmaggot', requiredKillCount: 80, saveName: 'Maggots', location: '480190' },
    { name: 'Slubberlug', requiredKillCount: 12, saveName: 'Dustroach Pollywog', location: '478965' },
    { name: 'Muckroach', requiredKillCount: 20, saveName: 'Dustroach', location: '478264' },
    { name: 'Bloatroach', requiredKillCount: 12, saveName: 'Bloat Roach', location: '478737' },
    { name: 'Roachcatcher', requiredKillCount: 20, saveName: 'Roachfeeder Short', location: '478261' },
    { name: 'Roachfeeder', requiredKillCount: 20, saveName: 'Roachfeeder Tall', location: '478338' },
    { name: 'Roachkeeper', requiredKillCount: 10, saveName: 'Roachkeeper', location: '478697' },
    { name: 'Roachserver', requiredKillCount: 10, saveName: 'Roachkeeper Chef Tiny', location: '478991' },
    { name: 'Disgraced Chef Lugoli', requiredKillCount: 1, saveName: 'Roachkeeper Chef', location: '480346' },
    { name: 'Wraith', requiredKillCount: 10, saveName: 'Wraith', location: '478367' },
    { name: 'Mothleaf Lagnia', requiredKillCount: 25, saveName: 'Swamp Drifter', location: '478738' },
    { name: 'Miremite', requiredKillCount: 20, saveName: 'Swamp Goomba', location: '478966' },
    { name: 'Swamp Squit', requiredKillCount: 30, saveName: 'Swamp Mosquito', location: '478721' },
    { name: 'Spit Squit', requiredKillCount: 20, saveName: 'Swamp Mosquito Skinny', location: '480261' },
    { name: 'Stilkin', requiredKillCount: 15, saveName: 'Swamp Muckman', location: '480206' },
    { name: 'Stilkin Trapper', requiredKillCount: 12, saveName: 'Swamp Muckman Tall', location: '480238' },
    { name: 'Groal the Great', requiredKillCount: 1, saveName: 'Swamp Shaman', location: '480345' },
    { name: 'Barnak', requiredKillCount: 8, saveName: 'Swamp Barnacle', location: '478962' },
    { name: 'Ductsucker', requiredKillCount: 6, saveName: 'Swamp Ductsucker', location: '480211' },
    { name: 'Pond Skipper', requiredKillCount: 15, saveName: 'Pond Skater', location: '478159' },
    { name: 'Pondcatcher', requiredKillCount: 20, saveName: 'Pilgrim Fisher', location: '478161' },
    { name: 'Shellwood Gnat', requiredKillCount: 15, saveName: 'Shellwood Gnat', location: '478983' },
    { name: 'Wood Wasp', requiredKillCount: 12, saveName: 'Shellwood Wasp', location: '478160' },
    { name: 'Splinter', requiredKillCount: 12, saveName: 'Stick Insect', location: '478980' },
    { name: 'Splinterhorn', requiredKillCount: 10, saveName: 'Stick Insect Charger', location: '478169' },
    { name: 'Splinterbark', requiredKillCount: 10, saveName: 'Stick Insect Flyer', location: '478186' },
    { name: 'Sister Splinter', requiredKillCount: 1, saveName: 'Splinter Queen', location: '480324' },
    { name: 'Phacia', requiredKillCount: 25, saveName: 'Flower Drifter', location: '478168' },
    { name: 'Pollenica', requiredKillCount: 10, saveName: 'Bloom Shooter', location: '478175' },
    { name: 'Gahlia', requiredKillCount: 20, saveName: 'Bloom Puncher', location: '478181' },
    { name: 'Shrine Guardian Seth', requiredKillCount: 1, saveName: 'Seth', location: '480352' },
    { name: 'Nyleth', requiredKillCount: 1, saveName: 'Flower Queen', location: '480353' },
    { name: 'Furm', requiredKillCount: 25, saveName: 'Bell Goomba', location: '478194' },
    { name: 'Winged Furm', requiredKillCount: 12, saveName: 'Bell Fly', location: '478195' },
    { name: 'Pharlid', requiredKillCount: 20, saveName: 'Blade Spider', location: '479737' },
    { name: 'Pharlid Diver', requiredKillCount: 10, saveName: 'Blade Spider Hang', location: '478232' },
    { name: 'Shardillard', requiredKillCount: 3, saveName: 'Shell Fossil Mimic', location: '480162' },
    { name: 'Sandcarver', requiredKillCount: 40, saveName: 'Sand Centipede', location: '480191' },
    { name: 'Squirrm', requiredKillCount: 4, saveName: 'Coral Judge Child', location: '479862' },
    { name: 'Judge', requiredKillCount: 15, saveName: 'Coral Judge', location: '479736' },
    { name: 'Last Judge', requiredKillCount: 1, saveName: 'Last Judge', location: '480351' },
    { name: 'Coral Furm', requiredKillCount: 15, saveName: 'Coral Spike Goomba', location: '480363' },
    { name: 'Driznit', requiredKillCount: 25, saveName: 'Coral Conch Shooter', location: '478306' },
    { name: 'Driznarga', requiredKillCount: 14, saveName: 'Coral Conch Shooter Heavy', location: '480245' },
    { name: 'Pokenabbin', requiredKillCount: 16, saveName: 'Coral Conch Stabber', location: '480366' },
    { name: 'Conchfly', requiredKillCount: 8, saveName: 'Coral Conch Driller', location: '480369' },
    { name: 'Great Conchfly', requiredKillCount: 2, saveName: 'Coral Conch Driller Giant', location: '480335' },
    { name: 'Crustcrawler', requiredKillCount: 10, saveName: 'Coral Goombas', location: '480227' },
    { name: 'Crustcrag', requiredKillCount: 6, saveName: 'Coral Goomba Large', location: '480243' },
    { name: 'Kai', requiredKillCount: 10, saveName: 'Coral Swimmer Fat', location: '480231' },
    { name: 'Spinebeak Kai', requiredKillCount: 10, saveName: 'Poke Swimmer', location: '480235' },
    { name: 'Steelspine Kai', requiredKillCount: 15, saveName: 'Spike Swimmer', location: '480234' },
    { name: 'Yuma', requiredKillCount: 16, saveName: 'Coral Swimmer Small', location: '480233' },
    { name: 'Yumama', requiredKillCount: 3, saveName: 'Coral Big Jellyfish', location: '480232' },
    { name: 'Karaka', requiredKillCount: 10, saveName: 'Coral Warrior', location: '480229' },
    { name: 'Kakri', requiredKillCount: 10, saveName: 'Coral Flyer', location: '480230' },
    { name: 'Yago', requiredKillCount: 12, saveName: 'Coral Flyer Throw', location: '480228' },
    { name: 'Karak Gor', requiredKillCount: 8, saveName: 'Coral Brawler', location: '480225' },
    { name: 'Alita', requiredKillCount: 6, saveName: 'Coral Hunter', location: '480226' },
    { name: 'Corrcrust Karaka', requiredKillCount: 6, saveName: 'Coral Bubble Brute', location: '480224' },
    { name: 'Crust King Khann', requiredKillCount: 1, saveName: 'Coral King', location: '480327' },
    { name: 'Watcher at the Edge', requiredKillCount: 1, saveName: 'Coral Warrior Grey', location: '480326' },
    { name: 'Voltvyrm', requiredKillCount: 1, saveName: 'Zap Core Enemy', location: '480336' },
    { name: 'Drapefly', requiredKillCount: 30, saveName: 'Citadel Bat', location: '479013' },
    { name: 'Drapelord', requiredKillCount: 4, saveName: 'Citadel Bat Large', location: '480263' },
    { name: 'Drapemite', requiredKillCount: 20, saveName: 'Mite Heavy', location: '479004' },
    { name: 'Giant Drapemite', requiredKillCount: 6, saveName: 'Understore Mite Giant', location: '480005' },
    { name: 'Underworker', requiredKillCount: 15, saveName: 'Understore Small', location: '479512' },
    { name: 'Underscrub', requiredKillCount: 20, saveName: 'Pilgrim 03 Understore', location: '479746' },
    { name: 'Undersweep', requiredKillCount: 10, saveName: 'Pilgrim Staff Understore', location: '479837' },
    { name: 'Underpoke', requiredKillCount: 25, saveName: 'Understore Poker', location: '479510' },
    { name: 'Underloft', requiredKillCount: 25, saveName: 'Understore Thrower', location: '479511' },
    { name: 'Undercrank', requiredKillCount: 4, saveName: 'Understore Heavy', location: '479836' },
    { name: 'Envoy', requiredKillCount: 20, saveName: 'Song Pilgrim 01', location: '479897' },
    { name: 'Choir Pouncer', requiredKillCount: 30, saveName: 'Pilgrim 01 Song', location: '479885' },
    { name: 'Choir Hornhead', requiredKillCount: 15, saveName: 'Pilgrim 02 Song', location: '479887' },
    { name: 'Choir Bellbearer', requiredKillCount: 25, saveName: 'Pilgrim 03 Song', location: '479882' },
    { name: 'Choir Flyer', requiredKillCount: 20, saveName: 'Pilgrim 04 Song', location: '479886' },
    { name: 'Choir Elder', requiredKillCount: 6, saveName: 'Pilgrim Stomper Song', location: '479906' },
    { name: 'Choristor', requiredKillCount: 25, saveName: 'Song Pilgrim 03', location: '479883' },
    { name: 'Reed', requiredKillCount: 30, saveName: 'Song Reed', location: '479880' },
    { name: 'Grand Reed', requiredKillCount: 12, saveName: 'Song Reed Grand', location: '479918' },
    { name: 'Choir Clapper', requiredKillCount: 3, saveName: 'Song Heavy Sentry', location: '480052' },
    { name: 'Clawmaiden', requiredKillCount: 10, saveName: 'Song Handmaiden', location: '479899' },
    { name: 'Memoria', requiredKillCount: 2, saveName: 'Arborium Keeper', location: '480239' },
    { name: 'Minister', requiredKillCount: 15, saveName: 'Song Administrator', location: '480050' },
    { name: 'Maestro', requiredKillCount: 6, saveName: 'Song Pilgrim Maestro', location: '480049' },
    { name: 'Second Sentinel', requiredKillCount: 1, saveName: 'Song Knight', location: '480348' },
    { name: 'Dreg Husk', requiredKillCount: 8, saveName: 'Song Threaded Husk', location: '480036' },
    { name: 'Dregwheel', requiredKillCount: 8, saveName: 'Song Threaded Husk Spin', location: '480043' },
    { name: 'Surgeon', requiredKillCount: 3, saveName: 'Song Pilgrim 02', location: '480409' },
    { name: 'Mortician', requiredKillCount: 10, saveName: 'Song Creeper', location: '480040' },
    { name: 'The Unravelled', requiredKillCount: 1, saveName: 'Conductor Boss', location: '480354' },
    { name: 'Cogwork Underfly', requiredKillCount: 25, saveName: 'Understore Automaton', location: '480021' },
    { name: 'Cogwork Hauler', requiredKillCount: 12, saveName: 'Understore Automaton EX', location: '480022' },
    { name: 'Cogwork Crawler', requiredKillCount: 15, saveName: 'Song Automaton Goomba', location: '479962' },
    { name: 'Cogworker', requiredKillCount: 15, saveName: 'Song Automaton Fly', location: '479938' },
    { name: 'Cogwork Spine', requiredKillCount: 10, saveName: 'Song Automaton Fly Spike', location: '479963' },
    { name: 'Cogwork Choirbug', requiredKillCount: 20, saveName: 'Song Automaton 01', location: '479961' },
    { name: 'Cogwork Cleanser', requiredKillCount: 12, saveName: 'Song Automaton 02', location: '479968' },
    { name: 'Cogwork Defender', requiredKillCount: 8, saveName: 'Song Automaton Shield', location: '479982' },
    { name: 'Cogwork Clapper', requiredKillCount: 1, saveName: 'Song Automaton Ball', location: '479971' },
    { name: 'Cogwork Dancers', requiredKillCount: 1, saveName: 'Clockwork Dancer', location: '480347' },
    { name: 'Vaultborn', requiredKillCount: 20, saveName: 'Song Scholar Acolyte', location: '480008' },
    { name: 'Lampbearer', requiredKillCount: 20, saveName: 'Lightbearer', location: '479994' },
    { name: 'Scrollreader', requiredKillCount: 15, saveName: 'Scrollkeeper', location: '479991' },
    { name: 'Vaultkeeper', requiredKillCount: 10, saveName: 'Scholar', location: '479999' },
    { name: 'Trobbio', requiredKillCount: 1, saveName: 'Trobbio', location: '480343' },
    { name: 'Tormented Trobbio', requiredKillCount: 1, saveName: 'Tormented Trobbio', location: '480344' },
    { name: 'Penitent', requiredKillCount: 8, saveName: 'Slab Prisoner Leaper New', location: '479005' },
    { name: 'Puny Penitent', requiredKillCount: 6, saveName: 'Slab Prisoner Fly New', location: '479006' },
    { name: 'Freshfly', requiredKillCount: 20, saveName: 'Slab Fly Small Fresh', location: '480479' },
    { name: 'Scabfly', requiredKillCount: 15, saveName: 'Slab Fly Small', location: '479008' },
    { name: 'Guardfly', requiredKillCount: 10, saveName: 'Slab Fly Mid', location: '479007' },
    { name: 'Wardenfly', requiredKillCount: 8, saveName: 'Slab Fly Large', location: '479011' },
    { name: 'Broodmother', requiredKillCount: 1, saveName: 'Slab Fly Broodmother', location: '480338' },
    { name: 'Driftlin', requiredKillCount: 20, saveName: 'Peaks Drifter', location: '479036' },
    { name: 'Mnemonid', requiredKillCount: 10, saveName: 'Crystal Drifter', location: '479043' },
    { name: 'Mnemonord', requiredKillCount: 3, saveName: 'Crystal Drifter Giant', location: '480198' },
    { name: 'Servitor Ignim', requiredKillCount: 8, saveName: 'Weaver Servitor', location: '478215' },
    { name: 'Servitor Boran', requiredKillCount: 5, saveName: 'Weaver Servitor Large', location: '479041' },
    { name: 'Winged Lifeseed', requiredKillCount: 8, saveName: 'Lifeblood Fly', location: '479858' },
    { name: 'Plasmid', requiredKillCount: 15, saveName: 'Bone Worm BlueBlood', location: '480146' },
    { name: 'Plasmidas', requiredKillCount: 6, saveName: 'Bone Worm BlueTurret', location: '480331' },
    { name: 'Plasmified Zango', requiredKillCount: 1, saveName: 'Blue Assistant', location: '479273' },
    { name: 'Leaf Glider', requiredKillCount: 12, saveName: 'Lilypad Fly', location: '480218' },
    { name: 'Leaf Roller', requiredKillCount: 10, saveName: 'Grass Goomba', location: '480217' },
    { name: 'Pendra', requiredKillCount: 10, saveName: 'Hornet Dragonfly', location: '480223' },
    { name: 'Pendragor', requiredKillCount: 10, saveName: 'Dragonfly Large', location: '480481' },
    { name: 'Nuphar', requiredKillCount: 6, saveName: 'Lilypad Trap', location: '480222' },
    { name: 'Cloverstag', requiredKillCount: 10, saveName: 'Cloverstag', location: '480221' },
    { name: 'Palestag', requiredKillCount: 1, saveName: 'Cloverstag White', location: '480321' },
    { name: 'Kindanir', requiredKillCount: 10, saveName: 'Grasshopper Child', location: '480215' },
    { name: 'Verdanir', requiredKillCount: 10, saveName: 'Grasshopper Slasher', location: '480219' },
    { name: 'Escalion', requiredKillCount: 10, saveName: 'Grasshopper Fly', location: '480220' },
    { name: 'Clover Dancers', requiredKillCount: 1, saveName: 'Clover Dancer', location: '480322' },
    { name: 'Shadow Creeper', requiredKillCount: 16, saveName: 'Abyss Crawler', location: '480134' },
    { name: 'Shadow Charger', requiredKillCount: 6, saveName: 'Abyss Crawler Large', location: '480135' },
    { name: 'Gloomsac', requiredKillCount: 15, saveName: 'Gloomfly', location: '480133' },
    { name: 'Gargant Gloom', requiredKillCount: 4, saveName: 'Gloom Beast', location: '480132' },
    { name: 'Void Tendrils', requiredKillCount: 1, saveName: 'Void Tendrils', location: '479744' },
    { name: 'Void Mass', requiredKillCount: 8, saveName: 'Black Thread Core', location: '480418' },
    { name: 'Summoned Saviour', requiredKillCount: 1, saveName: 'Abyss Mass', location: '480310' },
    { name: 'Wingmould', requiredKillCount: 10, saveName: 'White Palace Fly', location: '480415' },
    { name: 'Garpid', requiredKillCount: 30, saveName: 'Centipede Trap', location: '479626' },
    { name: 'Imoba', requiredKillCount: 4, saveName: 'Spike Lazy Flyer', location: '479627' },
    { name: 'Skrill', requiredKillCount: 10, saveName: 'Surface Scuttler', location: '479628' },
    { name: 'Bell Eater', requiredKillCount: 1, saveName: 'Giant Centipede', location: '480350' },
    { name: 'Huge Flea', requiredKillCount: 1, saveName: 'Giant Flea', location: '479122' },
    { name: 'Shakra', requiredKillCount: 1, saveName: 'Shakra', location: '479822' },
    { name: 'Garmond & Zaza', requiredKillCount: 1, saveName: 'Garmond_Zaza', location: '479361' },
    { name: 'Lost Garmond', requiredKillCount: 1, saveName: 'Garmond', location: '480325' },
    { name: 'Pinstress', requiredKillCount: 1, saveName: 'Pinstress Boss', location: '480337' },
    { name: 'Widow', requiredKillCount: 1, saveName: 'Spinner Boss', location: '480323' },
    { name: 'First Sinner', requiredKillCount: 1, saveName: 'First Weaver', location: '480339' },
    { name: 'Phantom', requiredKillCount: 1, saveName: 'Phantom', location: '480356' },
    { name: 'Lace', requiredKillCount: 2, saveName: 'Lace', location: '480355' },
    { name: 'Grand Mother Silk', requiredKillCount: 1, saveName: 'Silk Boss', location: '480342' },
    { name: 'Lost Lace', requiredKillCount: 1, saveName: 'Lost Lace', location: '480341' }
];

