export const mapList = [
    { name: "Mosslands", location: "", flag: "" },
    { name: "The Marrow", location: "", flag: "" },
    { name: "Deep Docks", location: "", flag: "" },
    { name: "Hunter's March", location: "", flag: "" },
    { name: "Far Fields", location: "", flag: "" },
    { name: "Greymoor", location: "", flag: "" },
    { name: "Bellhart", location: "", flag: "" },
    { name: "Shellwood", location: "", flag: "" },
    { name: "Wormways", location: "", flag: "" },
    { name: "Weavenest Atla", location: "", flag: "" },
    { name: "Blasted Steps", location: "", flag: "" },
    { name: "Sinner's Road", location: "", flag: "" },
    { name: "Grand Gate", location: "", flag: "" },
    { name: "Underworks", location: "", flag: "" },
    { name: "Choral Chambers", location: "", flag: "" },
    { name: "Whispering Vaults", location: "", flag: "" },
    { name: "Whiteward", location: "", flag: "" },
    { name: "Cogwork Core", location: "", flag: "" },
    { name: "Memorium", location: "", flag: "" },
    { name: "High Halls", location: "", flag: "" },
    { name: "The Slab", location: "", flag: "" },
    { name: "Mount Fay", location: "", flag: "" },
    { name: "Bilewater", location: "", flag: "" },
    { name: "Putrified Ducts", location: "", flag: "" },
    { name: "Sands of Karak", location: "", flag: "" },
    { name: "The Cradle", location: "", flag: "" },
    { name: "Verdania", location: "", flag: "" },
    { name: "The Abyss", location: "", flag: "" },
];