export const mapList = [
    { name: "Mosslands", location: "", flag: "HasMossGrottoMap" },
    { name: "The Marrow", location: "", flag: "HasBoneforestMap" },
    { name: "Deep Docks", location: "", flag: "HasDocksMap" },
    { name: "Hunter's March", location: "", flag: "HasHuntersNestMap" },
    { name: "Far Fields", location: "", flag: "HasWildsMap" },
    { name: "Greymoor", location: "", flag: "HasGreymoorMap" },
    { name: "Bellhart", location: "", flag: "HasBellhartMap" },
    { name: "Shellwood", location: "", flag: "HasShellwoodMap" },
    { name: "Wormways", location: "", flag: "HasCrawlMap" },
    { name: "Weavenest Atla", location: "", flag: "HasWeavehomeMap" },
    { name: "Blasted Steps", location: "", flag: "HasJudgeStepsMap" },
    { name: "Sinner's Road", location: "", flag: "HasHangMap" },
    { name: "Grand Gate", location: "", flag: "HasSongGateMap" },
    { name: "Underworks", location: "", flag: "HasCitadelUnderstoreMap" },
    { name: "Choral Chambers", location: "", flag: "HasCoralMap" },
    { name: "Whispering Vaults", location: "", flag: "HasLibraryMap" },
    { name: "Whiteward", location: "", flag: "HasWardMap" },
    { name: "Cogwork Core", location: "", flag: "HasCogMap" },
    { name: "Memorium", location: "", flag: "HasArboriumMap" },
    { name: "High Halls", location: "", flag: "HasHallsMap" },
    { name: "The Slab", location: "", flag: "HasSlabMap" },
    { name: "Mount Fay", location: "", flag: "HasPeakMap" },
    { name: "Bilewater", location: "", flag: "HasSwampMap" },
    { name: "Putrified Ducts", location: "", flag: "HasAqueductMap" },
    { name: "Sands of Karak", location: "", flag: "HasCoralMap" },
    { name: "The Cradle", location: "", flag: "HasCradleMap" },
    { name: "Verdania", location: "", flag: "HasCloverMap" },
    { name: "The Abyss", location: "", flag: "HasAbyssMap" },
];