export const ToolList = [
    // red tools
    { name: "Straight Pin", location: "", saveName: "Straight Pin" },
    { name: "Threefold Pin", location: "", saveName: "Tri Pin" },
    { name: "Sting Shard", location: "", saveName: "Sting Shard" },
    { name: "Tacks", location: "", saveName: "Tack" },
    { name: "Longpin", location: "", saveName: "Harpoon" },
    { name: "Curveclaw", location: "", saveName: "Curve Claws" },
    { name: "Curvesickle", location: "", saveName: "" },
    { name: "Throwing Ring", location: "", saveName: "Shakra Ring" },
    { name: "Pimpillo", location: "", saveName: "Pimpilo" },
    { name: "Conchcutter", location: "", saveName: "Conch Drill" },
    { name: "Silkshot (Forge Daughter)", location: "", saveName: "Webshot Forge" },
    { name: "Silkshot (Twelfth Architect)", location: "", saveName: "" },
    { name: "Silkshot (Mount Fay)", location: "", saveName: "" },
    { name: "Delver's Drill", location: "", saveName: "Screw Attack" },
    { name: "Cogwork Wheel", location: "", saveName: "Cogwork Saw" },
    { name: "Cogfly", location: "", saveName: "Cogwork Flier" },
    { name: "Rosary Cannon", location: "", saveName: "Rosary Cannon" },
    { name: "Flintslate", location: "", saveName: "Flintstone" },
    { name: "Snare Setter", location: "", saveName: "" },
    { name: "Flea Brew", location: "", saveName: "" },
    { name: "Plasmium Phial", location: "", saveName: "Lifeblood Syringe" },
    { name: "Needle Phial", location: "", saveName: "Extractor" },
    { name: "Voltvessels", location: "", saveName: "Lightning Rod" },
    // blue tools
    { name: "Druid's Eye", location: "", saveName: "Mosscreep Tool 1" },
    { name: "Druid's Eyes", location: "", saveName: "" },
    { name: "Magma Bell", location: "", saveName: "Lava Charm" },
    { name: "Warding Bell", location: "", saveName: "Bell Bind" },
    { name: "Pollip Pouch", location: "", saveName: "Poison Pouch" },
    { name: "Fractured Mask", location: "", saveName: "Fractured Mask" },
    { name: "Multibinder", location: "", saveName: "Multibind" },
    { name: "Weavelight", location: "", saveName: "White Ring" },
    { name: "Sawtooth Circlet", location: "", saveName: "Brolly Spike" },
    { name: "Injector Band", location: "", saveName: "Quickbind" },
    { name: "Spool Extender", location: "", saveName: "Spool Extender" },
    { name: "Resserve Bind", location: "", saveName: "Reserve Bind" },
    { name: "Claw Mirror", location: "", saveName: "Dazzle Bind" },
    { name: "Claw Mirrors", location: "", saveName: "Dazzle Bind Upgraded" },
    { name: "Memory Crystal", location: "", saveName: "Revenge Crystal" },
    { name: "Snitch Pick", location: "", saveName: "Thief Claw" },
    { name: "Volt Filament", location: "", saveName: "Zap Imbuement" },
    { name: "Quick Sling", location: "", saveName: "Quick Sling" },
    { name: "Wreath of Purity", location: "", saveName: "Maggot Charm" },
    { name: "Longclaw", location: "", saveName: "Longneedle" },
    { name: "Wispfire Lantern", location: "", saveName: "Wisp Lantern" },
    { name: "Egg of Flealia", location: "", saveName: "Flea Charm" },
    { name: "Pin Badge", location: "", saveName: "Pinstress Tool" },
    // yellow tools
    { name: "Compass", location: "", saveName: "Compass" },
    { name: "Shard Pendant", location: "", saveName: "Bone Necklace" },
    { name: "Magnetite Brooch", location: "", saveName: "Rosary Magnet" },
    { name: "Weighted Belt", location: "", saveName: "Weighted Anklet" },
    { name: "Barbed Bracelet", location: "", saveName: "Barbed Wire" },
    { name: "Dead Bug's Purse", location: "", saveName: "Dead Mans Purse" },
    { name: "Shell Satchel", location: "", saveName: "" },
    { name: "Magnetite Dice", location: "", saveName: "Magnetite Dice" },
    { name: "Scuttlebrace", location: "", saveName: "" },
    { name: "Ascendant's Grip", location: "", saveName: "Wallcling" },
    { name: "Spider Strings", location: "", saveName: "Musician Charm" },
    { name: "Silkspeed Anklets", location: "", saveName: "Sprintmaster" },
    { name: "Thief's Mark", location: "", saveName: "Thief Charm" },
]

export const ToolLiquidList = [
     { name: "Flea Brew", location: "", saveName: "Flea Brew" },    
]

export const silkShotList = [
    { name: "Silkshot (Forge Daughter)", location: "", flag: "ForgeDaughterMentionedWebShot"}
]