export const ToolList = [
    // red tools
    { name: "Straight Pin", location: "", flag: "" },
    { name: "Threefold Pin", location: "", flag: "" },
    { name: "Sting Shard", location: "", flag: "" },
    { name: "Tacks", location: "", flag: "" },
    { name: "Longpin", location: "", flag: "" },
    { name: "Curveclaw", location: "", flag: "" },
    { name: "Curvesickle", location: "", flag: "" },
    { name: "Throwing Ring", location: "", flag: "" },
    { name: "Pimpillo", location: "", flag: "" },
    { name: "Conchcutter", location: "", flag: "" },
    { name: "Silkshot (Forge Daughter)", location: "", flag: "" },
    { name: "Silkshot (Twelfth Architect)", location: "", flag: "" },
    { name: "Silkshot (Mount Fay)", location: "", flag: "" },
    { name: "Delver's Drill", location: "", flag: "" },
    { name: "Cogwork Wheel", location: "", flag: "" },
    { name: "Cogfly", location: "", flag: "" },
    { name: "Rosary Cannon", location: "", flag: "" },
    { name: "Flintslate", location: "", flag: "" },
    { name: "Snare Setter", location: "", flag: "" },
    { name: "Flea Brew", location: "", flag: "" },
    { name: "Plasmium Phial", location: "", flag: "" },
    { name: "Needle Phial", location: "", flag: "" },
    { name: "Voltvessels", location: "", flag: "" },
    // blue tools
    { name: "Druid's Eye", location: "", flag: "" },
    { name: "Druid's Eyes", location: "", flag: "" },
    { name: "Magma Bell", location: "", flag: "" },
    { name: "Warding Bell", location: "", flag: "" },
    { name: "Pollip Pouch", location: "", flag: "" },
    { name: "Fractured Mask", location: "", flag: "" },
    { name: "Multibinder", location: "", flag: "" },
    { name: "Weavelight", location: "", flag: "" },
    { name: "Sawtooth Circlet", location: "", flag: "" },
    { name: "Injector Band", location: "", flag: "" },
    { name: "Spool Extender", location: "", flag: "" },
    { name: "Resserve Bind", location: "", flag: "" },
    { name: "Claw Mirror", location: "", flag: "" },
    { name: "Claw Mirrors", location: "", flag: "" },
    { name: "Memory Crystal", location: "", flag: "" },
    { name: "Snitch Pick", location: "", flag: "" },
    { name: "Volt Filament", location: "", flag: "" },
    { name: "Quick Sling", location: "", flag: "" },
    { name: "Wreath of Purity", location: "", flag: "" },
    { name: "Longclaw", location: "", flag: "" },
    { name: "Wispfire Lantern", location: "", flag: "" },
    { name: "Egg of Flealia", location: "", flag: "" },
    { name: "Pin Badge", location: "", flag: "" },
    // yellow tools
    { name: "Compass", location: "", flag: "" },
    { name: "Shard Pendant", location: "", flag: "" },
    { name: "Magnetite Brooch", location: "", flag: "" },
    { name: "Weighted Belt", location: "", flag: "" },
    { name: "Barbed Bracelet", location: "", flag: "" },
    { name: "Dead Bug's Purse", location: "", flag: "" },
    { name: "Shell Satchel", location: "", flag: "" },
    { name: "Magnetite Dice", location: "", flag: "" },
    { name: "Scuttlebrace", location: "", flag: "" },
    { name: "Ascendant's Grip", location: "", flag: "" },
    { name: "Spider Strings", location: "", flag: "" },
    { name: "Silkspeed Anklets", location: "", flag: "" },
    { name: "Thief's Mark", location: "", flag: "" },
]